services:
  - type: web
    name: talentlink-backend
    env: python
    plan: free
    buildCommand: cd Talent-Link-main/backend && pip install Django==6.0.2 djangorestframework==3.16.1 django-cors-headers==4.9.0 python-dotenv==1.2.2 Pillow==12.1.1 gunicorn && python manage.py migrate
    startCommand: cd Talent-Link-main/backend && python -m gunicorn backend.wsgi:application --bind 0.0.0.0:$PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: ALLOWED_HOSTS
        value: .onrender.com
